### ISSUE TITLE
Tests do not run through with current GH Core

### ISSUE THREAD

**Issue by karussell** [graphhopper/map-matching#102]
Failed tests: 
  MatchServletTest.testDoPost:71 expected:<9> but was:<7>

This is probably due to our "duplicate point"-clean up @boldtrn ?

**Comment by boldtrn** [comment]
> This is probably due to our "duplicate point"-clean up @boldtrn ?

No, this is not yet deployed :). The reason should be the updated PathSimplification which results in less returned points. Haven't looked at the test though.
