### ISSUE TITLE
Matched path exceeds gpx trace at first and last nodes

### ISSUE THREAD

**Issue by LothbrokR** [graphhopper/map-matching#104]
Hello,

I am working on a project where I need to match gps traces on osm map.

The traces I have consist in a series of lat/lon points that represent a road segment for which I want to find the matching osm road segment.

I first convert the lat/lon values to a gpx file then use the map-matching feature to get the result.

My problem can be illustrated in the following image, where the matched path exceeds my gps trace at both the beginning and end. What is also strange is that the matching is reported to have a 0.07% difference while we can clearly see that the represented green path is much longer than the black path.

![screenshot](https://user-images.githubusercontent.com/13240983/31177461-662b320c-a916-11e7-8cb5-661212bc38b1.png)

This is the gpx file I used for the above screenshot:

[120+00085_13643.zip](https://github.com/graphhopper/map-matching/files/1355896/120.00085_13643.zip)

Do you have any suggestions on why this is happening ?

**Comment by karussell** [comment]
Please use our forum for questions:
https://discuss.graphhopper.com/c/graphhopper/map-matching

I think your question is related to #51

**Comment by LothbrokR** [comment]
Okey, thank you for the fast reply.
