### ISSUE TITLE
The code  on Master  compilation failed

### ISSUE THREAD

**Issue by solderain** [graphhopper/map-matching#107]
Pull the master code and try to compile, but it  did not pass , get the error below ,cann't get dependency code for "graphhopper-reader-osm:jar:0.10-SNAPSHOT"
@karussell

**Comment by boldtrn** [comment]
You are using repo.alibaba-inc.com and not one of the official repos. Try again with the default settings and let us know if the issue is resolved.

**Comment by solderain** [comment]
@boldtrn  
Thanks for your remind，have changed the repository to central , see the below screenshot , it didn't work well still , not sure any wrong configuration 
![image](https://user-images.githubusercontent.com/4144738/32536543-84224cfe-c424-11e7-8c75-a3dae2e850b9.png)

**Comment by karussell** [comment]
Why was there a need to edit the pom.xml? Also lets move to https://discuss.graphhopper.com/c/graphhopper/map-matching Furthermore you should switch to the 0.9.0 stable version

**Comment by solderain** [comment]
@karussell  I couldn't find 0.9.0 stable version in all branchs , how to  pull  that version?

**Comment by karussell** [comment]
0.9

**Comment by karussell** [comment]
Ups, it is not yet created. Will do this

**Comment by solderain** [comment]
Got it , thanks !
