### ISSUE TITLE
Snapping is way off

### ISSUE THREAD

**Issue by AAAstorga** [graphhopper/map-matching#111]
As you can see in the image below, the snapping is way off. Any idea why this is the case?

<img width="487" alt="screen shot 2018-02-23 at 11 07 33 pm" src="https://user-images.githubusercontent.com/15990084/36625487-60c01a42-18ee-11e8-8bcd-378ba7578024.png">

Best,
Austin

**Comment by karussell** [comment]
For questions please use our forum. Highly likely you used a vehicle that has no access to those ways.
