### ISSUE TITLE
How to get map-matching coordinate one to one?

### ISSUE THREAD

**Issue by mengzhangli** [graphhopper/map-matching#114]
Hi~ It's a good map-matching tool and I really appreciate your effort!
However, when I implemented this tool, i.e.  input the coordinates (*.gpx file) and it returns corrected map-matching(*.gpx.res.gpx file), the length of them is not the same.  The algorithm of literature shows the input and output are one-to-one. I'm wondering whether there is certain params that I left out. 
THX for your answer!

**Comment by mengzhangli** [comment]
NOTE:  The code I use is the version from @karussell . I just saw it upgraded this week which I'm not try yet.

**Comment by karussell** [comment]
Please use our forum for discussion and questions.
