### ISSUE TITLE
Map matching snaps from entrance to exit ramp

### ISSUE THREAD

**Issue by otbutz** [graphhopper/map-matching#122]
Overview;
![matching-overview](https://user-images.githubusercontent.com/22315436/42168625-cb708312-7e11-11e8-9960-17e9db4c06ef.png)
Snapping:
![matching-detail](https://user-images.githubusercontent.com/22315436/42168634-cf94fed2-7e11-11e8-8222-6f2952e3a9d7.png)

Expectation:
![expectation](https://user-images.githubusercontent.com/22315436/42168484-5f47deba-7e11-11e8-9a48-f86723db33dd.png)

Minimum working example:
```xml
<?xml version="1.0"?>
<gpx xmlns:wptx1="http://www.garmin.com/xmlschemas/WaypointExtension/v1" xmlns:gpxedw="http://www.gpxeditor.co.uk/xmlschemas/WaypointExtension/v1" xmlns:gpxedts="http://www.gpxeditor.co.uk/xmlschemas/TrackSegExtension/v1" xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" creator="GPXEditor" version="1.1" xmlns="http://www.topografix.com/GPX/1/1">
  <trk>
    <name>Untitled</name>
    <trkseg>
      <trkpt lat="51.28604" lon="6.90011" />
      <trkpt lat="51.28792" lon="6.89951" />
      <trkpt lat="51.28995" lon="6.89887" />
      <trkpt lat="51.29173" lon="6.89833" />
      <trkpt lat="51.29301" lon="6.89793" />
      <trkpt lat="51.29496" lon="6.89758" />
      <trkpt lat="51.29656" lon="6.89739" />
      <trkpt lat="51.29729" lon="6.89857" />
      <trkpt lat="51.2985" lon="6.89936" />
      <trkpt lat="51.29768" lon="6.89443" />
      <trkpt lat="51.29677" lon="6.89173" />
      <trkpt lat="51.29508" lon="6.88726" />
      <trkpt lat="51.29403" lon="6.88514" />
      <trkpt lat="51.29284" lon="6.88295" />
    </trkseg>
  </trk>
</gpx>
```

**Comment by michaz** [comment]
Works for me, result looks almost like your expectation.

What version are you using? Any custom network data (other than regular OSM)? On your screenshot, it almost looks like there are edges going through mid-air..

**Comment by otbutz** [comment]
> Any custom network data (other than regular OSM)?

Going to report back after i tested it with most recent OSM data but that might be an explanation.

**Comment by michaz** [comment]
Closing for now.
