### ISSUE TITLE
Question about map matching rules

### ISSUE THREAD

**Issue by OtavioHBL** [graphhopper/map-matching#129]
Hey guys, i am working on a project and i was wonering if there is any way to change the way that the map matching algorithm "sees" the .gpx file. For example, the algorithm respects the streets orientation, but, if I wanted to change this and get the real sampled locations, regardless of street rules or things like that, will it be possible? thanks

**Comment by michaz** [comment]
Hey, please move to the forum for general questions.

.. but this sounds like you might want to try to map-match based on walking, not driving.

**Comment by OtavioHBL** [comment]
Hey,

no man, it's based on driving.

**Comment by OtavioHBL** [comment]
Basically, i want the real route travelled by a vehicle, regardless of street orientation or any kind of transit rules. Sorry if I have not made myself clear.

**Comment by OtavioHBL** [comment]
@michaz could you please re-open this topic? I really need help about this ^^
