### ISSUE TITLE
Can I match CSV traces against the map?

### ISSUE THREAD

**Issue by Sherleen** [graphhopper/map-matching#136]
The trajectory I want to match is in CSV file.
However, when I perform `java -jar matching-web/target/graphhopper-map-matching-web-0.12-SNAPSHOT.jar match matching-core/src/test/resources/*.csv`, it will have problems.
Therefore, I would like to know if this repo support csv file and if there are some requirements for csv file format.

**Comment by karussell** [comment]
For questions please use our forum. (you can only use gpx files at the moment not csv)
