### ISSUE TITLE
How to use properties file from Routing? graph.ch.weightings: [] is not equal to loaded [fastest|car]

### ISSUE THREAD

**Issue by anonym24** [graphhopper/map-matching#139]
There are some differences between OSM files for "**Map Matching**" and "**Routing**"

"Map Matching" doesn't work with files of Routing

For "Map Matching":

java -jar matching-web/target/graphhopper-map-matching-web-*.jar import *.osm.pbf

![image](https://user-images.githubusercontent.com/8851301/48905055-21bfe100-ee69-11e8-9e84-0e2e6953e307.png)

For "Routing":

./graphhopper.sh -a import -i <your-osm-file>

![image](https://user-images.githubusercontent.com/8851301/48905069-2e443980-ee69-11e8-893d-934fd1f3f504.png)

![image](https://user-images.githubusercontent.com/8851301/48905073-3308ed80-ee69-11e8-9e7c-17950c36452e.png)

So there are some differences in `proporties` file 

When I use properties file form Routing for MapMathing I get the next error:

```
 java.lang.IllegalStateException: Configured graph.ch.weightings: [] is not equal to loaded [fastest|car]
     at com.graphhopper.storage.GraphHopperStorage.loadExisting(GraphHopperStorage.java:254)
     at com.graphhopper.GraphHopper.load(GraphHopper.java:781)
     at com.graphhopper.matching.MatchCommand.<init>(MatchCommand.java:45)
     at com.example.gpstrack.Map.onConnected(Map.java:811)
```

In my app I want to use routing and map matching at the same time and use the same files 

It seems I need two instance of Graphhopper anyway:

        graphHopperRouting.load("*/graphhopper/country-gh");

        graphHopperMapMatching.getCHFactoryDecorator().setEnabled(false);
        graphHopperMapMatching.load(("*/graphhopper/country-gh");

But how to init the same files? If could init different proporties files, something like this:

![image](https://user-images.githubusercontent.com/8851301/48905332-f38ed100-ee69-11e8-835d-1db81b7c0c14.png)

But I believe default constructor of Graphhopper class won't allow such manipulations, it expects path to the folder

**Comment by karussell** [comment]
Please use our forum for usage questions.

**Comment by anonym24** [comment]
@karussell I guess this isn't just question, it can be considered as an issue or even feature request

**Comment by anonym24** [comment]
@karussell I asked that question on the forum https://discuss.graphhopper.com/t/how-to-use-properties-file-from-routing-graph-ch-weightings-is-not-equal-to-loaded-fastest-car/3806
it's almost a week without answer
