### ISSUE TITLE
Strange behavior in response time

### ISSUE THREAD

**Issue by holydrinker** [graphhopper/map-matching#145]
Hi guys,
I'm playing with GraphHopper API, and I noticed a strange behavior.

This is what I do:
- I choose a series of 24 gps point
- I perform map matching using on the website ([here](http://bit.ly/2Twpyc2) is my request with points already inserted)
- I perform map matching in my scala application using the java dependencies _graphhopper-reader-osm v0.9.0_ and  _graphhopper-map-matching-core v0.10.0_

My question is about the response time. I used the chrome console to check the response time from the website, and I timed just the "doWork" function in my code.

- Response time from website: about 80ms
- Response time from java application: about 800ms

How can this be possible? Is a normal behavior or am I missing something?
Thank you very much.

**Comment by karussell** [comment]
Questions should go to the forum.

> How can this be possible?

You should update your dependencies. Read the map matching part here https://www.graphhopper.com/blog/2018/09/24/september-news-from-graphhopper/
