### ISSUE TITLE
how i make the .pbf file by myself, i want to test another file, but my file format is .shp, any way to convert the format? Please help 

### ISSUE THREAD

**Issue by wangjnchuan** [graphhopper/map-matching#150]
For general questions or discussion about GraphHopper, please use our [forum](https://discuss.graphhopper.com).

The best way to get help about an GraphHopper issue is to create a valid and detailed issue content, preferable with a unit or integration test reproducing the issue. 
Please include the version of GraphHopper, the JVM and the operating system are you
using. Also tell us your expected result via screenshot or similar.

If you have an Android application using GraphHopper, please **always** post to the [forum](https://discuss.graphhopper.com/c/graphhopper/graphhopper-ios-and-android) before and include logs and the version of your Android.

**Comment by karussell** [comment]
> For general questions or discussion about GraphHopper, please use our forum.

You have already answered your question here ;)
