### ISSUE TITLE
Unexpected Matching Behavior

### ISSUE THREAD

**Issue by sobhan-moosavi** [graphhopper/map-matching#152]
I realized for some traces, the matched trace is significantly different from the original one. Especially for those parts of a trajectory closer to its origin and/or destination. See attached image as an example (the pink part is not part of the input trace but is included in the matched trace), with the gpx file attached as well. Would you please help me to realize what is the source of this issue? 

Thanks

![trajectory](https://user-images.githubusercontent.com/18216929/60207770-b25a0780-9824-11e9-86d9-50cf65d35ad1.png)

[449845923207.gpx.zip](https://github.com/graphhopper/map-matching/files/3331595/449845923207.gpx.zip)

**Comment by karussell** [comment]
I can reproduce the issue with a GPS accuracy of up to 40. Increasing it to 50 solved the problem though. Can you confirm this? (I suspect the algo has no other choice when the data is too weak)

**Comment by sobhan-moosavi** [comment]
Thanks for checking. I was also able to get reasonable result when used 50 as GPS accuracy. As I have a large set of trajectories with some of them having low accurate GPS data, would that hurt if I use a large accuracy (say 100) to map match all of them? 

Thanks

**Comment by karussell** [comment]
The most real (restrictive) setting is better IMO. If you don't know this, maybe only increase this if the distance discrepancy is too big or some other workaround
