### ISSUE TITLE
Failue in case that the very last two points of a track have exactly the same location

### ISSUE THREAD

**Issue by ratrun** [graphhopper/map-matching#17]
One of my tracks contains two exactly same located waypoints at the very end of the track. In this case the algortihm fails. I have made a test and a hack solution which solves this case, see

https://github.com/graphhopper/map-matching/commit/992998dd829815f4cebc2961c828b49b9affc844

This hack solves the problem I had. I didn't test if two consecutive nodes at an arbitrary location somewhere in between the first and the last waypoint of a track would be also a problem and if the change would work in such a case.

**Comment by karussell** [comment]
Do you have an example where this occurs?

**Comment by ratrun** [comment]
Sorry, currently I can't reproduce the issue any more. Maybe because of the recent change in maxSearchMultiplier=50 to maxSearchMultiplier=100. I'll need to do some more tests, but his may take a while.

**Comment by ratrun** [comment]
I have tried a lot to reproduce the issue without success. I have changed too much in the meantime (OSM input file, graphhopper-web, parameters).

**Comment by karussell** [comment]
Ok, feel free to reopen at any time :)
