### ISSUE TITLE
Last point of map-matched output lies too far from actual route

### ISSUE THREAD

**Issue by bonobo1** [graphhopper/map-matching#176]
Map matching of some .gpx files yields a good result, however, a point is very often added at the end, which lies very far from the actual route.

[In this file](https://github.com/graphhopper/map-matching/files/4774402/output.zip) four _.gpx_ files are included.  **output_bad.gpx**, **output_good.gpx** are the files that are going to be map matched (should have changed the name). **output_bad.gpx.res.gpx** and **output_good.gpx.res.gpx** contain the map matched routes.

Run this with the two files **output_bad.gpx**, **output_good.gpx** in _folder_.
```java -jar ~/graphhopper_new/map-matching/matching-web/target/graphhopper-map-matching-web-1.0-SNAPSHOT.jar match ~/folder/*.gpx```

Both files yield a good result, however **output_bad.gpx.res.gpx** appends a point, which lies hundreds of kilometers away. This behavior is noticed very often.

### Wrong output
**output_bad.gpx** is **red** (input for map matching)
**output_bad.gpx.res.gpx** is **blue** (output of map matching)
![bad](https://user-images.githubusercontent.com/39952894/84566254-0df00e80-ad70-11ea-9741-23d14e10bd21.png)

### Expected ouput
**output_good.gpx** is **red** (input for map matching)
**output_good.gpx.res.gpx** is **blue** (output of map matching)
![good](https://user-images.githubusercontent.com/39952894/84566292-47287e80-ad70-11ea-80ce-28659b5fc244.png)

Running on Ubuntu 18.04

**Comment by michaz** [comment]
Ah, no, wait, I got it. Thanks.

**Comment by michaz** [comment]
Seems to have magically fixed itself -- I get it on the version you were working from, but don't get it on 1.0 / current master (as of today).

Can you confirm?

**Comment by bonobo1** [comment]
Sorry for not replying; will test in the following days and let you know if the problem persists
