### ISSUE TITLE
Fail to build recent-Core (27 July 2020)

### ISSUE THREAD

**Issue by braito4** [graphhopper/map-matching#180]
[INFO] Reactor Summary for GraphHopper Map Matching Parent Project 2.0-SNAPSHOT:
[INFO] 
[INFO] GraphHopper Map Matching Parent Project ............ SUCCESS [  0.004 s]
[INFO] hmm-lib ............................................ SUCCESS [  3.518 s]
[INFO] GraphHopper Map Matching ........................... FAILURE [  1.759 s]
[INFO] GraphHopper Map Matching Dropwizard Bundle ......... SKIPPED
[INFO] GraphHopper Map Matching Web ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.430 s
[INFO] Finished at: 2020-07-27T16:48:13+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project graphhopper-map-matching-core: Could not resolve dependencies for project com.graphhopper:graphhopper-map-matching-core:jar:2.0-SNAPSHOT: Failed to collect dependencies at com.graphhopper:graphhopper-reader-osm:jar:d32a20d4c5c107039e72482517085dd213f57631: Failed to read artifact descriptor for com.graphhopper:graphhopper-reader-osm:jar:d32a20d4c5c107039e72482517085dd213f57631: Could not transfer artifact com.graphhopper:graphhopper-reader-osm:pom:d32a20d4c5c107039e72482517085dd213f57631 from/to github (https://maven.pkg.github.com/graphhopper/graphhopper): Authentication failed for https://maven.pkg.github.com/graphhopper/graphhopper/com/graphhopper/graphhopper-reader-osm/d32a20d4c5c107039e72482517085dd213f57631/graphhopper-reader-osm-d32a20d4c5c107039e72482517085dd213f57631.pom 401 Unauthorized -> [Help 1]

**Comment by karussell** [comment]
You need to set your github credentials or do not rely on github packages and use the occasionally released pre-releases.

**Comment by rocinant** [comment]
I am pretty new to maven build, and currently I used IDEA, after opening the project with idea I get the "Cannot resolve com.graphhopper:graphhopper-reader-osm:1f5419977ed205d48d5507b65fae231592e52c5b" error, then I tried to put server github with my username and password into maven's setting.xml, then I get error "Could not transfer artifact com.graphhopper:graphhopper-reader-osm:jar:1f5419977ed205d48d5507b65fae231592e52c5b from/to github (https://maven.pkg.github.com/graphhopper/graphhopper): Failed to transfer file https://maven.pkg.github.com/graphhopper/graphhopper/com/graphhopper/graphhopper-reader-osm/1f5419977ed205d48d5507b65fae231592e52c5b/graphhopper-reader-osm-1f5419977ed205d48d5507b65fae231592e52c5b.jar with status code 400", what am I missing here to solve the problem, please.

**Comment by karussell** [comment]
If you have problems with github packages just use a version released on maven central (current lastest is 2.0)

**Comment by rocinant** [comment]
> If you have problems with github packages just use a version released on maven central (current lastest is 2.0)

For these who have similary problem, go to https://github.com/settings/tokens, log in, and generate the Personal access token, then set this token to settings.xml for your maven used in idea seems solve the problem.
