### ISSUE TITLE
Suggestion: More precision

### ISSUE THREAD

**Issue by Alby1987** [graphhopper/map-matching#2]
During the matching algorithm, the software can do an extra check to remove spurious errors. The program may check the edge of the point, and check one (two-customizable) points backwards and one (two-customizable) points forwards to see if their edge is in a street that's on the same class. If the point before (x-1) and after (x+1) are on a highway, and x is not on a motorway, you can do an extra check if the point is near a motorway, and ignore it if it so. Could this be a right idea?

**Comment by karussell** [comment]
I'll close this for now, as currently there are no real world examples which make the map-matching failing for this scenario. Please reopen if you encounter such issues!
