### ISSUE TITLE
Mapping sidewalk

### ISSUE THREAD

**Issue by karthim** [graphhopper/map-matching#22]
I am working on a project to infer the sidewalk from the GPX traces that are collected while the person is walking. The map-matching algorithm works perfectly to map the GPS points to the road, but is there any way i can infer which side of the road the user is walking. This would enable me to tag where the sidewalk is available on the street (i.e., right/left side of the road). I would appreciate, if you can could throw some pointers on how to achieve this with the graph hopper based map-matcher.

**Comment by karussell** [comment]
Thanks for this request and feedback. You could calculate this via the QueryResult and the way geometry. But problems will start if GPS signal has to large error tolerance and indifferent results will come.

**Comment by karthim** [comment]
Thanks for the response. I am able to use the fetchGeometry to infer the side of the road. Is it possible to get the OSM properties of the edgematch. For example for a edgematch I would like to know if it is on the highway or footway.

**Comment by karussell** [comment]
See https://discuss.graphhopper.com/t/map-matching-osm-id-output/528 if it does not help, please ask there.
