### ISSUE TITLE
src/main/resources/log4j.xml overriding client log configuration

### ISSUE THREAD

**Issue by SausagePie** [graphhopper/map-matching#27]
The src/main/resources/log4j.xml is interfering with my own logging configuration.
Suggest that you move your log4j.xml to src/test/resources.

Log4j attempts to load log4j.xml first, and then log4j.properties, using the first it finds on the classpath.

I have my own logging configuration (log4j.properties). Your log4j.xml is being picked up instead.

I can workaround it, but this is something you might like to clean up.

Some related discussion:
http://stackoverflow.com/questions/10890505/multiple-log4j-properties-files-in-classpath?rq=1

**Comment by karussell** [comment]
Okay, related to https://github.com/graphhopper/graphhopper/issues/250

**Comment by devemux86** [comment]
I'd vote for that too.

Also somehow related to [graphhopper/graphhopper#494](https://github.com/graphhopper/graphhopper/issues/494).

**Comment by karussell** [comment]
Will be fixed with https://github.com/graphhopper/graphhopper/pull/1334
