### ISSUE TITLE
Cannot import data - error 

### ISSUE THREAD

**Issue by lilouch** [graphhopper/map-matching#28]
Hi,

When I ran this command:
./map-matching.sh action=import datasource=/home/map-matching/map-data/leipzig_germany.osm.pbf

I got this error:
ipzig_germany.osm.pbf
ls: cannot access target/map-matching-*-dependencies.jar: No such file or directory
[INFO] Scanning for projects...
Downloading: https://oss.sonatype.org/content/groups/public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
Downloading: http://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.graphhopper:map-matching:0.5-SNAPSHOT (/home/isg/Desktop/map-matching/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact org.sonatype.oss:oss-parent:pom:9 from/to sonatype-oss-public (https://oss.sonatype.org/content/groups/public/): oss.sonatype.org: No address associated with hostname and 'parent.relativePath' points at no local POM @ line 17, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
Error: Unable to access jarfile action=import

Maven and Java are installed. 
The output of echo $JAVA_HOME is the following: /usr/lib/jvm/java-7-openjdk-amd64/jre

Can you help me ?

Thanks,

**Comment by karussell** [comment]
Strange, maybe sonatype is offline? Would you try 0.4 instead of the 0.5 snapshot (just change the branch to 0.4 and try again)

**Comment by lilouch** [comment]
No still not working.

I was thinking: If I used a proxy, could still work ?

**Comment by karussell** [comment]
No, idea. Never worked with proxies.

Can you access the sonatype and maven central repos?
https://oss.sonatype.org/content/groups/public/

**Comment by lilouch** [comment]
Yes I'm able to go to the Maven repo of the website.

**Comment by lilouch** [comment]
Okey A friend test the software without proxy and he didn't have the errors above except this one: Error: Unable to access jarfile action=import

So do you know for this error ? For the proxy, I'll try to see how I can deal with...I don't know if in the program I have to put some proxy parameters.

Thanks

**Comment by karussell** [comment]
if you cannot download the dependencies there is no other way to build it and therefor it cannot find the created jar file.

**Comment by karussell** [comment]
What you can try is to specify the proxy for the JVM: http://stackoverflow.com/questions/120797/how-do-i-set-the-proxy-to-be-used-by-the-jvm

**Comment by karussell** [comment]
We've fixed the script, can you try again with the latest version?
