### ISSUE TITLE
Date import fails

### ISSUE THREAD

**Issue by linux-devil** [graphhopper/map-matching#32]
After cloning , I tried running following :
 ./map-matching.sh action=import datasource=/home/harshit.sharma/random.osm 

LocationIndexMatch.java:[67,31] error: method findNetworkEntries in class LocationIndexTree cannot be applied to given types. 

Following is stacktrace:
ls: cannot access target/map-matching-*-dependencies.jar: No such file or directory
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building GraphHopper Map Matching 0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ map-matching ---
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ map-matching ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ map-matching ---
[INFO] Compiling 6 source files to /home/harshitsharma/map-matching/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.117s
[INFO] Finished at: Fri Aug 07 16:24:45 IST 2015
[INFO] Final Memory: 12M/143M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project map-matching: Compilation failure
[ERROR] /home/harshitsharma/map-matching/src/main/java/com/graphhopper/matching/LocationIndexMatch.java:[67,31] error: method findNetworkEntries in class LocationIndexTree cannot be applied to given types;
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error: Unable to access jarfile action=import

**Comment by karussell** [comment]
The reason is probably due to latest change in graphhopper core 0.5-SNAPSHOT. You should be able to fix this when switching to the stable 0.4 branch (git checkout 0.4) or wait a few days until 0.5 is released.

**Comment by karussell** [comment]
Please re-open if it remains a problem for you.

**Comment by oubenal** [comment]
Same problem as well. not resolved yet ?

**Comment by karussell** [comment]
Please try switching to the latest stable version 0.6.0 or print your compilation error log

**Comment by oubenal** [comment]
i fixed the problem by installing the right maven (maven 3 instead of 2)
and java(1.7 instead of 1.6) . You can precise such information at the wiki
or somewhere else !

2016-05-18 15:16 GMT+02:00 Peter <notifications@github.com>:

**Comment by karussell** [comment]
See https://github.com/graphhopper/map-matching/commit/db4c11090c5ab43367905b92eb5e57524464717a
