### ISSUE TITLE
Slicing the GPX leads to orientation errors

### ISSUE THREAD

**Issue by zzottel** [graphhopper/map-matching#33]
With most GPX trails I tested map-matching with, I'm getting orientation errors with most separatedSearchDistance values, except when I set separatedSearchDistance to very high values so that the trail will be sliced only very few times or not at all.

The tests were done with GPX files where there is a GPS point every one second or every two seconds.

As far as I can see, the problem seems to occur when by chance, the start of a new slice of the GPX file is where the current GPS point is closer to a street that leads away from the actual street driven than to that street itself.

If required, I can provide GPX files showing the issue, but I'll do so only directly to you, not via publicly visible means.

**Comment by leoroos** [comment]
I experienced the exact same problem. Usually the application then stops with a CouldNotFindMatchingPath Error.

**Comment by karussell** [comment]
We've introduced a new algorithm in master which will fix these tuning problems. Please try again with the master and report back!
