### ISSUE TITLE
All vehicles in input data 

### ISSUE THREAD

**Issue by jwisniewski100** [graphhopper/map-matching#34]
I need to process data from 24h when somebody can use all vehicle.
After  hopper.importOrLoad(); I can't change settings. How can I prepare map-matching for a large number of different routes?

**Comment by karussell** [comment]
Not sure if this is currently possible but should be easy to achieve as on import you just need to specify setEncodingManager(new EncodingManager("car", "bike", ...)) and on matching you need to set the vehicle you need.

**Comment by jwisniewski100** [comment]
for: setEncodingManager(new EncodingManager("car, bike, foot")) works perfectly
thanks a lot!
