### ISSUE TITLE
PostGIS map matching adaptor/plugin

### ISSUE THREAD

**Issue by nik-ffm** [graphhopper/map-matching#36]
I feel really stupid to ask this, but I can't make head or tail of the readme. Is the only valid input format a GPX file? Actually I have my points stored within PostGIS and I'm searching for an easy way to map it to OSM. Any ideas?

**Comment by karussell** [comment]
You should be able with a bit Java knowledge to ask postgis directly and use an importer or search a gpx exporter in the interweb ;)

**Comment by karussell** [comment]
As we now have a web UI this should be similar to this one: https://github.com/graphhopper/graphhopper/blob/master/core/files/postgis/gh_from_a_to_b_local.sql
