### ISSUE TITLE
Arguments not parsed

### ISSUE THREAD

**Issue by ruipgil** [graphhopper/map-matching#40]
When running this the arguments given to ``` main ``` don't get parsed.

When running ``` ./map-matching.sh action=import datasource=file.pbf ```
the arguments passed to ``` CmdArgs.read ``` are ``` ["action=import datasource=file.pbf"] ``` and not ``` ["action=import", "datasource=file.pbf"] ```. Consequently when getting the action it gets ``` "import datasource=file.pbf" ``` and it's empty for the datasource.

I've made a small adjustment to run it locally, if it's an issue I can make a PR, but not sure if it's just me.

Anyway, I'm running on OSX El Capitain, and I'm using zsh
```
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```

Running this in a docker container (maven:3.3.3-jdk-8), with bash and without the changes, also causes this problem.

Thank you

**Comment by karussell** [comment]
Can you update to the latest master. Should have been fixed ealier :)
https://github.com/graphhopper/map-matching/commit/0fa74fbeefd4a587a2aa6ac19d340b1ab72e6ec8
