### ISSUE TITLE
can the input gps traces file contain just point ? 

### ISSUE THREAD

**Issue by xuleihuanying** [graphhopper/map-matching#42]
Hi,
I want to match some points to the road network with the ESRI's shp file(point layer and road network layer). I try to convert the shp file to gpx format and run it in your software, error 'gpx list needs at least 2 points' appears. So, can the input gps traces file contain just point ? what should I do ?

**Comment by karussell** [comment]
Please use our forum: 
https://discuss.graphhopper.com/

**Comment by karussell** [comment]
Try with the recent master or as I said please use the forum.
