### ISSUE TITLE
map-matching SNAPSHOT versions

### ISSUE THREAD

**Issue by devemux86** [graphhopper/map-matching#46]
Is there a SNAPSHOT version for map-matching following the corresponding GraphHopper one and according to the master version in pom.xml?

i.e. `0.7-SNAPSHOT` in https://oss.sonatype.org/content/groups/public/com/graphhopper/

**Comment by karussell** [comment]
Currently not automatically deployed but you should be able to always use the latest master from GH core.

**Comment by devemux86** [comment]
Sorry Peter, I didn't understand. I use the latest master from GH.
I'm asking how we can use the latest master from map-matching without building the code.

**Comment by karussell** [comment]
> I'm asking how we can use the latest master from map-matching without building the code.

Sorry, I meant with "not automatically deployed" that you would need to build it yourself from code. (There is no such process yet like it is the case for GH)

**Comment by karussell** [comment]
This depends a bit on this issue https://github.com/bmwcarit/hmm-lib/issues/4 although this is currently in the works ...

**Comment by karussell** [comment]
Will now deployed regularly with the core if no errors. For now this is just a workaround using hmm lib as if it were 'our' module.

**Comment by karussell** [comment]
BTW: should we rename graphhopper-map-matching to graphhopper-map-matching-core similarly like we renamed graphhopper to graphhopper-core? Although this is not that important as it does not really conflict

**Comment by devemux86** [comment]
>should we rename graphhopper-map-matching to graphhopper-map-matching-core similarly like we renamed graphhopper to graphhopper-core?

You mean the artifactId in the pom ?

**Comment by karussell** [comment]
YEs

**Comment by devemux86** [comment]
Yes that could change, its folder has the `-core` already.

**Comment by karussell** [comment]
Ok, done
