### ISSUE TITLE
upgrade java versions here as well

### ISSUE THREAD

**Issue by karussell** [graphhopper/map-matching#48]
Related to graphhopper/graphhopper/issues/697 as master fails on travis otherwise

**Comment by devemux86** [comment]
Indeed as currently `map-matching` has failed tests:
```java
initializationError(com.graphhopper.matching.http.MatchServletTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.UnsupportedClassVersionError: com/graphhopper/http/GHServer : Unsupported major.minor version 52.0
```

**Comment by karussell** [comment]
Fixed now (only ran the tests so far)

**Comment by devemux86** [comment]
The tests pass if I run Maven via command line but not inside IntelliJ:
```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project map-matching-web: Compilation failure
```

**Comment by karussell** [comment]
hmmh, did you make sure you you either fetched the fresh deps for GH core or build them locally?

**Comment by karussell** [comment]
For Netbeans and the command line all seems fine though

**Comment by devemux86** [comment]
Yes command line works fine.

I retried with a clean clone and same result in IDE.
Clearly something with Java version. I'll have to check it.

**Comment by devemux86** [comment]
I just tested latest (Java 7/8) GH with a clean IntelliJ profile (system has JDK 7 & 8) and now it fails to build the graphhopper-web module.

The solution was to declare in IDE level that the projects have to use the JDK 8.
Though I was expecting that the Maven should take care of it completely. :worried:

**Comment by karussell** [comment]
> Though I was expecting that the Maven should have taken care of it. :worried: 

That is strange. Maybe an IntelliJ bug due to the mixed Java versions we use?

**Comment by devemux86** [comment]
Will need some testing.
It's supposed to honor the pom declarations and not needing to make changes via the IDE.
(BTW the problem happens with latest Idea 2016.1.1)
