### ISSUE TITLE
Possible problem with a less frequent GPX signal

### ISSUE THREAD

**Issue by karussell** [graphhopper/map-matching#6]
In the case if the GPX signal is not that frequent and the edge of one point P is rather short, this will reduce the impact of the weighting of the taken route through P and therefor could go another route without P.

One solution could be to insert artificial GPX points before and after P to reduce other edges close to P as well and increase probability that the routing engine uses a route through P.

**Comment by nside** [comment]
why not use the GPS course when it's available?

**Comment by karussell** [comment]
Not sure about your question. This issue is only about less frequent GPS signal. Currently one GPS point can only influence its edges around it. And if only one edge is on the path and this is short it could be that the algorithm ignores it. Maybe a picture can describe this better ... also a todo ;)

**Comment by karussell** [comment]
Will close. Should have added an example to see if this is now fixed.
