### ISSUE TITLE
Bus tracking

### ISSUE THREAD

**Issue by rasmusohrstig** [graphhopper/map-matching#62]
The matcher seems to assume that cars will obey traffic rules, for example by not taking shortcuts through roads that only allow buses. Example with bus only exit marked with red "B":

<img width="885" alt="bus_route" src="https://cloud.githubusercontent.com/assets/10023233/17816731/feb4a816-663a-11e6-97ef-5761952d91f9.png">

But what if the vehicle that we're trying to track is a bus? Any chance of implementing a vehicle option for buses?

**Comment by karussell** [comment]
See https://github.com/graphhopper/graphhopper/issues/223

Also one could implement a generic vehicle which allows more or less all roads accessible by a vehicle.
