### ISSUE TITLE
Allow matching to ignore direction

### ISSUE THREAD

**Issue by karussell** [graphhopper/map-matching#63]
Often the direction of a recorded track is not known or hard to determine. For those cases add a "ignore_direction=true" option

**Comment by michaz** [comment]
> Often the direction of a recorded track is not known or hard to determine.

When?

> A Track Segment holds a list of Track Points which are logically connected in order.
(GPX spec)

**Comment by michaz** [comment]
I think if a user indeed has a track which may be reversed, I would entice them to solve that on the client side and try the track in either direction.

**Comment by michaz** [comment]
> I think this could be just a user requirement, or wrongly mapped stuff or e.g. for bike people sometimes ignore oneways

Oh, I see _that_, but that would be a new `vehicle` in my book, not a changed map-matching algorithm.

> But we can also close here for now and reopen if we get real world examples.

Yup.
