### ISSUE TITLE
Feed with JSON

### ISSUE THREAD

**Issue by karussell** [graphhopper/map-matching#72]
Currently we accept GPX files, but JSON file (GeoJSON) would be nice too. We could reuse our work from https://github.com/graphhopper/graphhopper/pull/781

**Comment by kodonnell** [comment]
Possibly change this to creating a generic interface, with GPX and JSON as certain implementations? I suggest this as our data doesn't suit GPX (or a likely JSON format), which means I'm going to have to hack the source instead of extending it, which is a tad messy.

**Comment by karussell** [comment]
Ideally we could consume the same format the the web API of the core can return (type=json|gpx). And for JSON we currently not even return the time for every point but this would be nice to have.

For now I would prefer to have just one implementation and convert incoming data depending on the format. But you are right: instead of having everything like the entry objects tuned and named for GPX we should aim for something more generic ("measurement"?). I'm not sure what the benefits would be if we would make the "measurement" an interface.

**Comment by karussell** [comment]
Duplicate of #59
