### ISSUE TITLE
invalid API key for maps.omniscale

### ISSUE THREAD

**Issue by kodonnell** [graphhopper/map-matching#77]
Am I doing something wrong?

![img](https://cloud.githubusercontent.com/assets/8204904/20278222/b376f2e2-ab08-11e6-88fa-1d45c7b58fd3.png)

**Comment by karussell** [comment]
Fixed. You can also switch the map layer with the button on the top right. Also after the fix you can use the map tiles with our key on localhost but you cannot use them on your own server (get some fresh api keys at omniscale.com)
