### ISSUE TITLE
About the map matching algorithm used in the project

### ISSUE THREAD

**Issue by sniperLx** [graphhopper/map-matching#79]
Hi! I am finishing my paper's experiment based on this project, but the matching seem to perform not very good. So I wonder if you can show out the paper describing the matching algorithm used in the project. That will give me a lot help to read the source code and contribute something maybe. Thanks.

**Comment by oblonski** [comment]
Would you mind to be a bit more precise here? What do you mean by "seem to perform not very good"? If you could share your experiments, we might learn as well.

**Comment by karussell** [comment]
@sniperLx For discussion or questions please use our forum

**Comment by sniperLx** [comment]
[my matching result](http://i.imgur.com/DuknDIQ.png)
Thank your very much  for your reply.
Here is my matching result snapshot. The green dot is the observation gps point in my test track, and black dot is the matching result based on this project. My track was following the right side of the road. Unfortunately, the matching seem not to do as we expected.

**Comment by sniperLx** [comment]
@karussell Thanks for your reminding
