### ISSUE TITLE
missing long edges

### ISSUE THREAD

**Issue by kodonnell** [graphhopper/map-matching#84]
I've come across an issue where LocationIndexMatch isn't finding long edges. I am using a modified form of it, but I think the underlying issue may persist.

My (naive) understanding is `XFirstSearchCheck` basically is looping through nodes, and calculating the distance of the node to the query point, and this is then passed on to `XFirstSearchCheck.check` (which is where we do our thing). My concern is what happens on edges where there is a long separation between pillar nodes. For example

```
-----P1-----( ... N ... )-----P2-----
```

where the bracketed N is a search region around N, and P1/P2 are consecutive pillar nodes on an edge passing through the search region. In this case, neither P1 nor P2 are in the search region, and hence the edge won't (??) be included?

That all said ... I tried to create a test case for this, but it worked (i.e. the above didn't happen). I'm not sure whether it was just a bad test case, so I'm raising this 'issue' as more of a 'could be an issue if someone who knows more thinks it is'.

**Comment by karussell** [comment]
This should still work as we use BresenhamLine.calcPoints to fill in nodes if necessary and the two pillar nodes would be too far away. See some complex stuff with this discussed in https://github.com/graphhopper/graphhopper/pull/221 and https://github.com/graphhopper/graphhopper/issues/232 and http://stackoverflow.com/q/24679963/194609

**Comment by hbruch** [comment]
ProbabIy the issue I ran into is such a long edge issue. When trying to match a short track (with PR #109 applied). The red track in the image below with coords LINESTRING[8.576946438529065 48.942270883048046, 8.577063654245032 48.942225069201065] is not matched.
The blue lines represent the edges visited via XFirstSearchCheck.checkAdjacent. However, the long primary  B10 road is not visited.

<img width="516" alt="matching" src="https://user-images.githubusercontent.com/2187389/34068023-fb887420-e234-11e7-8e7c-9db78fb9cb81.png">

**Comment by karussell** [comment]
Thanks for the visual report. This is probably a bug in the feeding mechanism of the location index that works via the bresenham mechanism (as described in the linked issues), probably happens only under rare conditions.

**Comment by hbruch** [comment]
Ouch. In my case the road was tagged with access=no due to temporary road works. Sorry for hijacking this issue...
