### ISSUE TITLE
If a u-turn happens in the measured data the match could be truncated

### ISSUE THREAD

**Issue by karussell** [graphhopper/map-matching#85]
![map-matching-export](https://cloud.githubusercontent.com/assets/129644/20930529/fc21f908-bbcd-11e6-8f17-84ad182f404b.png)

Probably due to current code like `distanceCalc.calcDist() > 2 * measurementErrorSigma`? I guess, rather not, as I can reduce the gps accuracy to 15m (road is roughly 100m long) and still get the truncated snap. Also access to this road seems to be okay. I have the gpx file available here locally.

**Comment by kodonnell** [comment]
Hmmm, that's odd. Can you either post the GPX or

- confirm that it's not a visualization issue? I.e. that the road route doesn't actually go further up, but it's just not displayed?
- is it an 'inner link U-turn' (see #83)? I can see there's that little loop road off the U-turn road, but I'm not sure if that's valid for your vehicle. (If not, then it is an inner link U-turn.)
- try removing the return route, and see if you still get the same behaviour. Actually, getting it down to the minimum GPX list that shows the behaviour would be handy (though I can do that if you post it).

As an aside - is there a way we can add this to the codebase as a (currently) failing test? We obviously can, but then it'll fail builds etc. Can it be marked as more of a warning - so the build passes, but the user is still aware it's failing?

**Comment by karussell** [comment]
> Can you either post the GPX

Could send it to you per email (if you like or have time to investigate) or I will trim down or reproduce in another area so that we can add it without adding a new pbf.

> Can it be marked as more of a warning - so the build passes, but the user is still aware it's failing?

We could add it as a test that we tag with `@Ignore`, which should be listed separately I hope.

**Comment by kodonnell** [comment]
> Could send it to you per email (if you like or have time to investigate)

Happy either way.

> without adding a new pbf

That'd be best - though it's probably OK to add small pbfs (e.g. #83) using OSM export to select only the relevant region.

> We could add it as a test that we tag with @Ignore

Ah, that's cool. When you/I get the minimum example, do you want me to add a (failing) test? Or do you want to wait until we figure it out?

**Comment by karussell** [comment]
> When you/I get the minimum example, do you want me to add a (failing) test? Or do you want to wait until we figure it out?

Depends a bit on the type of the bug. If its hard to fix -> tag it with ignore

**Comment by kodonnell** [comment]
See [issue85.txt](https://github.com/graphhopper/map-matching/files/635195/issue85.txt) for a minimum example.

Can use [this](http://www.openstreetmap.org/export#map=16/48.2765/16.4516) export, but probably not a good idea to put into the repo unless there's an easy way to filter to only roads. (I will update my above comment.)

**Comment by karussell** [comment]
> unless there's an easy way to filter to only roads

Nice idea which we could apply to all existing osm files.

Maybe?
`osmosis --read-xml city.osm --tf accept-ways highway=* --used-node --write-xml highways.osm`

or somehow with https://wiki.openstreetmap.org/wiki/Osmconvert

**Comment by devemux86** [comment]
Also [Osmfilter](http://wiki.openstreetmap.org/wiki/Osmfilter).

**Comment by kodonnell** [comment]
Thanks both - created a [new issue](https://github.com/graphhopper/graphhopper/issues/903) so we can keep this one on track.

**Comment by michaz** [comment]
Seems to me like it wasn't disproven that this is an "inner-link U-turn", which, according to #83, we are modelling as "doesn't happen". So this is probably expected behavior.
