### ISSUE TITLE
Timedate parse issue

### ISSUE THREAD

**Issue by ustroetz** [graphhopper/map-matching#9]
I tried the following file as a test: https://www.openstreetmap.org/user/epe/traces/776904

The error I got is the following:
```
2015-02-12 14:59:45,897 [main] ERROR com.graphhopper.matching.MapMatchingMain - Problem with file 776904.gpx Error: java.text.ParseException: Unparseable date: "2010-07-30T17:5236"
```
What is the expected datetime format? Can we add this to the docs?

**Comment by karussell** [comment]
Looks like a problem with the data what is `17:5236`? There are several formats possible:

 * yyyy-MM-dd'T'HH:mm:ssZ
 * yyyy-MM-dd'T'HH:mm:ss'Z'
 * yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

See GPXFile and #3

And timezones (Z) can be in the format '+01:00'

**Comment by ustroetz** [comment]
Okay. I just picked a random sample from OSM traces. Maybe we can add the datetime format possibilities to the README.

**Comment by karussell** [comment]
Yes, sure. Even better we should support as many as possible ;)
