### ISSUE TITLE
Observing some considerable deviation

### ISSUE THREAD

**Issue by arminus** [graphhopper/map-matching#95]
I just gave the map-matcher a spin, here's an example of a DB built with the foot encoder and a GPX track downloaded from the web (i.e. not a raw/recorded track). There's quite some deviation at km 10-11 in the matched track on the right side and a smaller one at km 18/19. Are non-recorded tracks generally unsuited for the matcher or is there something else going on?

![rawvsmatched](https://cloud.githubusercontent.com/assets/683680/25350145/759714d0-2924-11e7-9bf1-43439092f9e5.jpg)

**Comment by arminus** [comment]
(I also tried bike and mtb encoders, same result)

**Comment by karussell** [comment]
If there are no paths in OSM how should GPS tracks be matched then? Or what do you mean? Also please move questions to our forum.

**Comment by karussell** [comment]
The difference at point "10" should be fixed in the latest master version. Did you try with master or a 0.8 release?
